### ISSUE TITLE
How to use the plugin

### ISSUE THREAD

**Issue by ray-x** [mfussenegger/nvim-lua-debugger#1]
Hi, I am trying use the plugin to debug lua plugin for neovim
The setup from README.md.  
`dap.lua`
```lua
local dap = require('dap')
dap.adapters.neovim = function(callback)
  local server = require('lua_debugger').launch()
  callback({ type = 'server'; host = server.host; port = server.port; })
end

dap.configurations.lua = {
  {
    type = 'neovim';
    request = 'attach';
    name = "Attach to running neovim instance";
  },
}
return dap
```

But when I launch the dap by using continue(), got a failure
`No stopped thread. Cannot move   `
The debug server seems to be launched with port 63191.
Is there additional setup need to do other than the README.md?
                                                                               
Thanks!

**Comment by mfussenegger** [comment]
The TODO items in the README are not checked-off because they haven't been implemented yet. I guess I shouldn't have put up usage/install instructions before it's useable.

You could check out [lua-debug.nvim](https://github.com/jbyuki/lua-debug.nvim) instead which I think is in a usable state.

**Comment by mfussenegger** [comment]
I updated the readme to refer to lua-debug.nvim and I'm going to archive this - no point in maintaining two nvim-lua debug adapters.
